Add GPT4o-mini model
deedy5/duckduckgo_search pull request #242
Opened 2024-08-01 20:13 UTC by mrgick

Hello @deedy5 

There is a model update on the duck.ai .
They added GPT4o-mini instead of gpt-3.5, but gpt-3.5 still works as well now
![image](https://github.com/user-attachments/assets/37d72878-2228-4f01-baed-410195a6ec32)

I have added the new model (GPT4o-mini) to your package

Test:
![image](https://github.com/user-attachments/assets/8268d4d4-cd10-40db-ad23-0090dab806c8)

Feel free to modify this PR as you wish.
Also, your package is awesome =)

2024-08-01 21:56 UTC, deedy5 commented on duckduckgo_search/version.py
> +__version__ = "6.2.6"
Please don't change the version in this PR

2024-08-01 21:56 UTC, deedy5 requested changes
Most likely `gpt-4o` is already responding instead of `gpt-3.5`. So just replace `gpt-3.5` with `gpt-4o`

2024-08-01 22:00 UTC, deedy5 requested changes
Also use the model name "gpt-4o-mini"

2024-08-01 22:06 UTC, deedy5 commented
@mrgick In short, change "gpt-3.5" to "gpt-4o-mini" everywhere.

2024-08-02 11:19 UTC, mrgick commented
Hello, @deedy5

Revert my last commit and replaced everywhere "gpt-3.5" with "gpt-4o-mini"

My test:
![image](https://github.com/user-attachments/assets/883f20ec-ab6a-4492-80d2-ca5a28fed534)

Pytest:
![image](https://github.com/user-attachments/assets/ddc6e7c4-2bbf-4fa6-a4c2-d6d8b42b1ae5)

2024-08-02 11:48 UTC, merged